//-----------------------------------------------------------------------
// This file is autogenerated
// Any changes to this file will be overwritten on build
// <auto-generated />
//-----------------------------------------------------------------------

namespace Cropper.Blazor.Client.Models
{
    public static partial class Snippets
    {
        public const string InstallationManualComponentsExample = @"@using Cropper.Blazor.Components

<CropperComponent Class=""cropper-example"" Src=""cropperblazor.png"" />

<style>
    .cropper-example {
        max-height: 200px;
        max-width: 200px;
    }
</style>";

        public const string InstallationManualCssFontsExample = @"<link href=""_content /Cropper.Blazor/cropper.min.css"" rel=""stylesheet"" />";

        public const string InstallationManualImportsExample = @"@using Cropper.Blazor.Components";

        public const string InstallationManualPackageExample = @"dotnet add package Cropper.Blazor";

        public const string InstallServicesNET5ServerExample = @"@* Dummy file do not remove, needed for content section *@";

        public const string InstallServicesNET5WasmExample = @"@* Dummy file do not remove, needed for content section *@";

        public const string InstallServicesNET6Example = @"using Cropper.Blazor.Extensions;

builder.Services.AddCropper();";

    }
}
