---
comment:
  require_changes: false
  behavior: "new"
  show_carryforward_flags: true

coverage:
  precision: 2
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

# Strict flag mapping for each .NET version and JS
flags:
  net:
    paths:
      - "src/Cropper.Blazor/Cropper.Blazor/Components"
      - "src/Cropper.Blazor/Cropper.Blazor/Events"
      - "src/Cropper.Blazor/Cropper.Blazor/Exceptions"
      - "src/Cropper.Blazor/Cropper.Blazor/Extensions"
      - "src/Cropper.Blazor/Cropper.Blazor/Models"
      - "src/Cropper.Blazor/Cropper.Blazor/Services"
    carryforward: false
  js:
    paths:
      - "src/Cropper.Blazor/Cropper.Blazor/Cropper/"
    carryforward: false
