---
comment:
  require_changes: false
  behavior: "new"
  show_carryforward_flags: true

coverage:
  precision: 2
  status:
    project:
      default:
        target: 80%
      dotnet:
        flags:
          - DotNet
        target: 100%
        threshold: 0%

      typescript:
        flags:
          - TypeScript
        target: 100%
        threshold: 0%

    patch:
      default:
        target: auto
      dotnet:
        flags:
          - DotNet
        target: 100%
        threshold: 0%

      typescript:
        flags:
          - TypeScript
        target: 6%
        threshold: 0%
