//-----------------------------------------------------------------------
// This file is autogenerated
// Any changes to this file will be overwritten on build
// <auto-generated />
//-----------------------------------------------------------------------

namespace Cropper.Blazor.Client.Models
{
    public static partial class Snippets
    {
        public const string ChangeAspectRatioExample = @"@using Cropper.Blazor.Models;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img"" @ref=""cropperComponent""
                                  Src=""images/Rivne2.jpg"" Options=""cropperOptions"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""CropBoxWidth"" Label=""Width"" Step=""100M"" Variant=""Variant.Text"" Min=""1""
                             Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Format=""N4"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""CropBoxHeight"" Label=""Height"" Step=""100M"" Variant=""Variant.Text"" Min=""1""
                             Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Format=""N4"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options cropperOptions = new Options
    {
        AspectRatio = 1m,
        ViewMode = ViewMode.Vm3
    };

    decimal _cropBoxWidth = 400;
    decimal _cropBoxHeight = 400;

    private decimal CropBoxWidth
    {
        get => _cropBoxWidth;
        set
        {
            _cropBoxWidth = value;
            cropperComponent!.SetAspectRatio(value / _cropBoxHeight);
            StateHasChanged();
        }
    }

    private decimal CropBoxHeight
    {
        get => _cropBoxHeight;
        set
        {
            _cropBoxHeight = value;
            cropperComponent!.SetAspectRatio(_cropBoxWidth / value);
            StateHasChanged();
        }
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string InitialAspectRatioExample = @"@using Cropper.Blazor.Models;

<div class=""img-container"">
    <CropperComponent Class=""big-img"" @ref=""cropperComponent"" Src=""images/Rivne.jpg""
                      Options=""cropperOptions"" />
</div>

@code {
    private CropperComponent? cropperComponent = null!;

    private Options cropperOptions = new Options
    {
        InitialAspectRatio = (decimal)1,
        AspectRatio = 0,
        ViewMode = ViewMode.Vm3
    };
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 800px;
    }
</style>";

        public const string MinMaxAspectRatioExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.CropMoveEvent;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img"" @ref=""cropperComponent"" Src=""images/Odesa.jpg""
                                  Options=""cropperOptions"" OnCropMoveEvent=""OnCropMoveEvent"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""minAspectRatio"" Label=""Min aspect ratio""
                             ReadOnly=""true"" HideSpinButtons=""true"">
            </MudNumericField>
            <MudNumericField Class=""mb-2"" @bind-Value=""maxAspectRatio"" Label=""Max aspect ratio""
                             ReadOnly=""true"" HideSpinButtons=""true"">
            </MudNumericField>
            <div class=""d-flex gap-x-6 align-end mb-2"">
                <MudChip T=""string"" Variant=""Variant.Outlined"" Color=""Color.Primary"" Class=""flex-1 ma-0 mt-4"">
                    Current aspect ratio:
                </MudChip>
                <MudNumericField @bind-Value=""CurrentAspectRatio"" Format=""N4"" Variant=""Variant.Text""
                                 HideSpinButtons=""true"" ReadOnly=""true"" Class=""flex-1"" />
            </div>
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;

    // Minimum and maximum aspect ratio settings
    private static decimal? minAspectRatio = 1;
    private static decimal? maxAspectRatio = 2;

    public decimal CurrentAspectRatio { get; set; } = 1;

    private Options cropperOptions = new Options
    {
        InitialAspectRatio = (decimal)1,
        AspectRatio = 0,
        ViewMode = ViewMode.Vm3
    };

    public async void OnCropMoveEvent(JSEventData<CropMoveEvent> cropMoveJSEvent)
    {
        CropBoxData cropBoxData = await cropperComponent!.GetCropBoxDataAsync();

        if (cropBoxData.Height != 0)
        {
            CurrentAspectRatio = cropBoxData.Width / cropBoxData.Height;

            if (minAspectRatio is not null || maxAspectRatio is not null)
            {
                if (CurrentAspectRatio < minAspectRatio)
                {
                    cropperComponent!.SetCropBoxData(new SetCropBoxDataOptions
                        {
                            Width = cropBoxData.Height * minAspectRatio
                        });
                }
                else if (CurrentAspectRatio > maxAspectRatio)
                {
                    cropperComponent!.SetCropBoxData(new SetCropBoxDataOptions
                        {
                            Width = cropBoxData.Height * maxAspectRatio
                        });
                }
            }
        }
        else
        {
            CurrentAspectRatio = 0;
        }
        StateHasChanged();
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string SetupAspectRatioExample = @"@using Cropper.Blazor.Models;

<div class=""img-container"">
    <CropperComponent Class=""big-img"" Options=""cropperOptions""
                      Src=""images/dolphin.jpg"" />
</div>

@code {
    private Options cropperOptions = new Options
    {
        AspectRatio = (decimal)16 / 9,
        ViewMode = ViewMode.Vm3
    };
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 800px;
    }
</style>";

        public const string BasicCropperUsageExample = @"@using Cropper.Blazor.Models

<CropperComponent Class=""big-img""
                  Src=""images/Rivne.jpg""
                  Options=""new Options()"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 500px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }
</style>";

        public const string CanvasCropperComponentTypeExample = @"@using Cropper.Blazor.Models

<div class=""cropper-canvas-container"">
    <CropperComponent @ref=""cropperComponent""
                      IsErrorLoadImage=""@IsErrorLoadImage""
                      ErrorLoadImageSrc=""images/error300px.png""
                      ErrorLoadImageClass=""error-image""
                      CropperComponentType=""CropperComponentType.Canvas""
                      InputAttributes=""@InputAttributes""
                      Options=""options"" />
</div>

@if (!IsErrorLoadImage)
{
    <div class=""button"" @onclick=""SetError"">
        Set Error
    </div>
}

<style>
    .cropper-canvas-container {
        max-height: 300px;
        width: 100%;
        /* These styles below are just needed for a nice button and don't related with cropper component */
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .error-image {
        filter: grayscale(100%);
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    [Inject] private IJSRuntime? JSRuntime { get; set; }

    private CropperComponent? cropperComponent = null!;
    private Options options;
    private bool IsErrorLoadImage { get; set; } = false;

    public Dictionary<string, object> InputAttributes { get; set; } = new Dictionary<string, object>
    {
        { ""id"", ""canvas-cropper"" }
    };

    protected override void OnInitialized()
    {
        options = new Options
        {

        };
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            // When using CropperComponentType.Canvas, the canvas element is used directly
            // instead of an <img> tag. This requires manually drawing or uploading an image
            // into the <canvas> element via JavaScript or library. Error handling (e.g., for failed image
            // loading) is also your responsibility in this case.
            // This approach is ideal when you’re building a drawing, painting, or image editing
            // tool where you need full control over the canvas content.
            ElementReference? canvasElementReference = cropperComponent!.GetCropperElementReference();

            // Example: Fill the canvas with random colors using JavaScript
            await JSRuntime!.InvokeVoidAsync(
                ""fillCanvasWithRandomColors"",
                canvasElementReference);

            // Initialize the cropper component after the canvas is ready
            cropperComponent.InitCropper();
        }

        await base.OnAfterRenderAsync(firstRender);
    }

    public void SetError()
    {
        // You can use 'ErrorLoadImageContent' instead of 'ErrorLoadImageSrc', 'ErrorLoadImageClass'
        // parameters in cropper component to set up custom error image content
        IsErrorLoadImage = true;
        cropperComponent!.Destroy();
    }
}";

        public const string CropperContainerExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Src=""cropperblazor.png"" Options=""new Options()"" />
</div>

<style>
    .img-container {
        max-height: 300px;
        width: 100%;
    }
</style>";

        public const string ImageLoadingErrorExample = @"@using Cropper.Blazor.Models

<CropperComponent Src=""incorrect-image-link""
                  ErrorLoadImageSrc=""images/error300px.png""
                  IsErrorLoadImage=""@IsErrorLoadImage""
                  OnErrorLoadImageEvent=""OnErrorLoadImageEvent""
                  Options=""new Options()"" />

<CropperComponent Src=""incorrect-image-link""
                  ErrorLoadImageSrc=""images/error300px.png""
                  ErrorLoadImageClass=""error-image""
                  IsErrorLoadImage=""@IsErrorLoadImage""
                  OnErrorLoadImageEvent=""OnErrorLoadImageEvent""
                  Options=""new Options()"" />
@code
{
    private bool IsErrorLoadImage { get; set; } = false;

    public void OnErrorLoadImageEvent(ErrorEventArgs errorEventArgs)
    {
        // You can use 'ErrorLoadImageContent' instead of 'ErrorLoadImageSrc', 'ErrorLoadImageClass'
        // parameters in cropper component to set up custom error image content
        IsErrorLoadImage = true;
        StateHasChanged();
    }
}

<style>
    .error-image {
        filter: grayscale(100%);
    }
</style>";

        public const string LoadCrossOriginImageExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Src=""cropperblazor.png""
                      Options=""options""
                      InputAttributes=""InputAttributes"" />
</div>

<style>
    .img-container {
        max-height: 300px;
        width: 100%;
    }
</style>

@code {
    private Options options;

    public Dictionary<string, object> InputAttributes { get; set; } = new Dictionary<string, object>
    {
        { ""crossorigin"", ""anonymous"" } // Another possible values: ""use-credentials"" or """" (the same as ""anonymous""). An invalid keyword and an empty string will be handled as the anonymous keyword. For more information see official https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin documentation
    };

    protected override void OnInitialized()
    {
        options = new Options
        {

        };
    }
}";

        public const string OverlayCropperComponentExample = @"@using Cropper.Blazor.Models;

<div class=""wrapper"">
    <CropperComponent Class=""big-img""
                      Src=""images/budir-church-bu-akirkja-iceland.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />

    <div class=""overlay-container"">
        <div class=""overlay-component"">
            Overlay cropper component
        </div>
    </div>
</div>

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .wrapper {
        position: relative;
        height: fit-content;
        width: fit-content;
        display: flex;
    }

    .overlay-container {
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        border-radius: 0.5rem;
        width: 100%;
        overflow: hidden;
    }

    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .overlay-container .overlay-component {
        height: 100%;
        width: 100%;
        display: inline-block;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        display: flex;
        justify-content: center;
        align-items: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? cropperComponent = null!;
}";

        public const string AdvancedCropExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""images/budir-church-bu-akirkja-iceland.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasAsync"">
    Get cropped image
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;

    public async Task GetCroppedCanvasAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        // Get a reference to a JavaScript cropped canvas object.
        CroppedCanvas croppedCanvas = await cropperComponent!.GetCroppedCanvasAsync(getCroppedCanvasOptions);
        // Invoke toDataURL JavaScript function from the canvas object.
        croppedCanvasDataURL = await croppedCanvas!.JSRuntimeObjectRef.InvokeAsync<string>(""toDataURL"", ""image/png"", 1);
    }
}";

        public const string BackgroundCropExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;
@using Cropper.Blazor.Exceptions;

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""images/budir-church-bu-akirkja-iceland.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasDataInBackgroundAsync"">
    Get cropped image in background
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;


    public async Task GetCroppedCanvasDataInBackgroundAsync()
    {
        // Define options for the cropped canvas, including size and image quality
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        // Call the cropper component to get the cropped canvas image
        ImageReceiver imageReceiver = await cropperComponent!.GetCroppedCanvasDataInBackgroundAsync(getCroppedCanvasOptions);

        try
        {
            // Retrieve the image stream from the receiver
            using MemoryStream croppedCanvasDataStream = await imageReceiver.GetImageChunkStreamAsync();

            // Convert the stream to a byte array
            byte[] croppedCanvasData = croppedCanvasDataStream.ToArray();

            // Encode the image data as a base64 data URL for use in HTML
            croppedCanvasDataURL = ""data:image/png;base64,"" + Convert.ToBase64String(croppedCanvasData);
        }
        catch (ImageProcessingException ex)
        {
            // Handle any image processing errors (currently empty - consider logging or rethrowing)
        }
    }
}";

        public const string BackgroundCropPolygonImageExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;
@using Cropper.Blazor.Exceptions;

<div class=""img-container cropper-face-pentagon"">
    <CropperComponent Class=""big-img""
                      Src=""images/Mushrooms.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasDataInBackgroundAsync"">
    Get cropped image in background
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .cropper-face {
        opacity: 25%;
    }

    .img-container.cropper-face-pentagon .cropper-container .cropper-crop-box .cropper-face {
        clip-path: polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%);
    }

    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    [Inject] private IJSRuntime? JSRuntime { get; set; }

    private CropperComponent? cropperComponent = null!;
    private string? croppedCanvasDataURL;

    public async Task GetCroppedCanvasDataInBackgroundAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        CroppedCanvasReceiver croppedCanvasReceiver = await cropperComponent!.GetCroppedCanvasInBackgroundAsync(
            getCroppedCanvasOptions,
            async (croppedCanvas, ct) =>
            {
                // Create an image receiver to receive the processed image data
                ImageReceiver imageReceiver = new ImageReceiver();

                try
                {
                    // Invoke a JavaScript function to apply elliptical background processing to the canvas,
                    // passing in the cropped canvas object and a .NET object reference for callback
                    await JSRuntime!.InvokeVoidAsync(
                        ""window.getPolygonImageInBackground"",
                        croppedCanvas!.JSRuntimeObjectRef,
                        // Defines a polygon using an SVG fill rule and a set of vertices previously defined in the following format styles:
                        // .img-container.cropper-face-pentagon.cropper-container.cropper-crop-box.cropper-face {
                        //     clip-path: polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%);
                        // }
                        // In our case, we need to pass the same data, but without the percent sign (%)
                        new int[] { 50, 0, 100, 38, 82, 100, 18, 100, 0, 38 },
                        DotNetObjectReference.Create(imageReceiver));

                    // Retrieve the image stream from the receiver
                    using MemoryStream croppedCanvasDataStream = await imageReceiver.GetImageChunkStreamAsync();

                    // Convert the stream to a byte array
                    byte[] croppedCanvasData = croppedCanvasDataStream.ToArray();

                    // Encode the image data as a base64 data URL for use in HTML
                    croppedCanvasDataURL = ""data:image/png;base64,"" + Convert.ToBase64String(croppedCanvasData);

                    // Force a UI refresh to reflect the new image
                    // This is required because we're in an async JS interop callback context,
                    // which runs outside of Blazor’s normal rendering/event loop.
                    // Calling StateHasChanged directly here might not work as expected
                    // because it may not execute on the Blazor synchronization context.
                    // InvokeAsync ensures StateHasChanged is called on the correct thread.

                    // Use InvokeAsync(StateHasChanged) in the following cases:
                    // 1. **JS Interop callbacks** – when data is updated via JS and needs a re-render.
                    // 2. **Background tasks** – when working with tasks outside the Blazor rendering context.

                    // **Be careful with InvokeAsync(StateHasChanged) in components with many elements or heavy rendering logic**:
                    // - Calling StateHasChanged frequently can cause **performance issues** if the component contains many UI elements.
                    // - Each call to StateHasChanged forces a full re-render of the component, which can be costly in large or complex components.
                    // - To mitigate this, consider breaking down your large components into **smaller, more manageable child components**.
                    // - **Smaller components** will re-render independently, reducing the overall re-render scope and improving performance.
                    await InvokeAsync(StateHasChanged);
                }
                catch (ImageProcessingException ex)
                {
                    // Handle any image processing errors (currently empty - consider logging or rethrowing)
                }
            });
    }
}";

        public const string BackgroundCropRoundImageExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;
@using Cropper.Blazor.Exceptions;

<div class=""img-container cropper-face-circle"">
    <CropperComponent Class=""big-img""
                      Src=""images/lone-tree.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasDataInBackgroundAsync"">
    Get cropped image  in background
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .cropper-face {
        opacity: 25%;
    }

    .img-container.cropper-face-circle .cropper-container .cropper-crop-box .cropper-face {
        border-radius: 50%;
    }

    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    [Inject] private IJSRuntime? JSRuntime { get; set; }

    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;

    public async Task GetCroppedCanvasDataInBackgroundAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        CroppedCanvasReceiver croppedCanvasReceiver = await cropperComponent!.GetCroppedCanvasInBackgroundAsync(
            getCroppedCanvasOptions,
            async (croppedCanvas, ct) =>
            {
                // Create an image receiver to receive the processed image data
                ImageReceiver imageReceiver = new ImageReceiver();

                try
                {
                    // Invoke a JavaScript function to apply elliptical background processing to the canvas,
                    // passing in the cropped canvas object and a .NET object reference for callback
                    await JSRuntime!.InvokeVoidAsync(
                        ""window.getEllipseImageInBackground"",
                        croppedCanvas!.JSRuntimeObjectRef,
                        DotNetObjectReference.Create(imageReceiver));

                    // Retrieve the image stream from the receiver
                    using MemoryStream croppedCanvasDataStream = await imageReceiver.GetImageChunkStreamAsync();

                    // Convert the stream to a byte array
                    byte[] croppedCanvasData = croppedCanvasDataStream.ToArray();

                    // Encode the image data as a base64 data URL for use in HTML
                    croppedCanvasDataURL = ""data:image/png;base64,"" + Convert.ToBase64String(croppedCanvasData);

                    // Force a UI refresh to reflect the new image
                    // This is required because we're in an async JS interop callback context,
                    // which runs outside of Blazor’s normal rendering/event loop.
                    // Calling StateHasChanged directly here might not work as expected
                    // because it may not execute on the Blazor synchronization context.
                    // InvokeAsync ensures StateHasChanged is called on the correct thread.

                    // Use InvokeAsync(StateHasChanged) in the following cases:
                    // 1. **JS Interop callbacks** – when data is updated via JS and needs a re-render.
                    // 2. **Background tasks** – when working with tasks outside the Blazor rendering context.

                    // **Be careful with InvokeAsync(StateHasChanged) in components with many elements or heavy rendering logic**:
                    // - Calling StateHasChanged frequently can cause **performance issues** if the component contains many UI elements.
                    // - Each call to StateHasChanged forces a full re-render of the component, which can be costly in large or complex components.
                    // - To mitigate this, consider breaking down your large components into **smaller, more manageable child components**.
                    // - **Smaller components** will re-render independently, reducing the overall re-render scope and improving performance.
                    await InvokeAsync(StateHasChanged);
                }
                catch (ImageProcessingException ex)
                {
                    // Handle any image processing errors (currently empty - consider logging or rethrowing)
                }
            });
    }
}";

        public const string BasicCropExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""images/budir-church-bu-akirkja-iceland.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasDataURLAsync"">
    Get cropped image
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;

    public async Task GetCroppedCanvasDataURLAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        croppedCanvasDataURL = await cropperComponent!.GetCroppedCanvasDataURLAsync(getCroppedCanvasOptions);
    }
}";

        public const string CropPolygonImageExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;

<div class=""img-container cropper-face-pentagon"">
    <CropperComponent Class=""big-img""
                      Src=""images/Mushrooms.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasAsync"">
    Get cropped image
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .cropper-face {
        opacity: 25%;
    }

    .img-container.cropper-face-pentagon .cropper-container .cropper-crop-box .cropper-face {
        clip-path: polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%);
    }

    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    [Inject] private IJSRuntime? JSRuntime { get; set; }

    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;

    public async Task GetCroppedCanvasAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        // Get a reference to a JavaScript cropped canvas object.
        CroppedCanvas croppedCanvas = await cropperComponent!.GetCroppedCanvasAsync(getCroppedCanvasOptions);
        // Invoke toDataURL JavaScript function from the canvas object.
        croppedCanvasDataURL = await JSRuntime!.InvokeAsync<string>(
            ""window.getPolygonImage"",
            croppedCanvas!.JSRuntimeObjectRef,
            // Defines a polygon using an SVG fill rule and a set of vertices previously defined in the following format styles:
            // .img-container.cropper-face-pentagon.cropper-container.cropper-crop-box.cropper-face {
            //     clip-path: polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%);
            // }
            // In our case, we need to pass the same data, but without the percent sign (%)
            new int[] { 50, 0, 100, 38, 82, 100, 18, 100, 0, 38 });
    }
}";

        public const string CropRoundImageExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;

<div class=""img-container cropper-face-circle"">
    <CropperComponent Class=""big-img""
                      Src=""images/lone-tree.jpg""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<div class=""button"" @onclick=""GetCroppedCanvasAsync"">
    Get cropped image
</div>

<img class=""cropped-img-container"" src=""@croppedCanvasDataURL"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .cropper-face {
        opacity: 25%;
    }

    .img-container.cropper-face-circle .cropper-container .cropper-crop-box .cropper-face {
        border-radius: 50%;
    }

    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    [Inject] private IJSRuntime? JSRuntime { get; set; }

    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;

    public async Task GetCroppedCanvasAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        // Get a reference to a JavaScript cropped canvas object.
        CroppedCanvas croppedCanvas = await cropperComponent!.GetCroppedCanvasAsync(getCroppedCanvasOptions);
        // Invoke toDataURL JavaScript function from the canvas object.
        croppedCanvasDataURL = await JSRuntime!.InvokeAsync<string>(""window.getEllipseImage"", croppedCanvas!.JSRuntimeObjectRef);
    }
}";

        public const string InvokeToDataURLExample = @"CroppedCanvas.JSRuntimeObjectRef.InvokeAsync&lt;string&gt;(""toDataURL"", type, encoderOptions);";

        public const string PrepareImageBeforeUploadToServerExample = @"@using Cropper.Blazor.Extensions;
@using Cropper.Blazor.Models;

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""icon-515x512.png""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

@if (decodedImageData is { base64ImageData: null, mediaType: null })
{
    <div class=""button"" @onclick=""GetDecodedImageDataAsync"">
        Get decoded image data
    </div>
}
else
{
    <MudText Typo=""Typo.body2"">
        Media type: @decodedImageData!.mediaType
    </MudText>
    <MudText Typo=""Typo.body2"" Class=""text-with-dots"">
        Base64: @decodedImageData!.base64ImageData
    </MudText>
    <MudText Typo=""Typo.body2"" Class=""text-with-dots"">
        Data URL: @croppedCanvasDataURL
    </MudText>
}

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* Means that the cropped image will take up 100% of the width of its containing element */
    .cropped-img-container {
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? cropperComponent = null!;
    private string croppedCanvasDataURL;
    private (string base64ImageData, string mediaType) decodedImageData;

    public async Task GetDecodedImageDataAsync()
    {
        GetCroppedCanvasOptions getCroppedCanvasOptions = new GetCroppedCanvasOptions
        {
            MaxHeight = 4096,
            MaxWidth = 4096,
            ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString()
        };

        croppedCanvasDataURL = await cropperComponent!.GetCroppedCanvasDataURLAsync(getCroppedCanvasOptions);
        decodedImageData = croppedCanvasDataURL.Decode();
    }
}";

        public const string CroppedDimensionsExample = @"@using Cropper.Blazor.Models;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""9"" lg=""9"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img"" @ref=""CropperComponent""
                                  Src=""images/Rivne2.jpg"" Options=""CropperOptions"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""9"" lg=""3"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""CropBoxWidth"" Label=""Width"" Step="".2M"" Variant=""Variant.Text""
                             Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Format=""N4"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""CropBoxHeight"" Label=""Height"" Step="".2M"" Variant=""Variant.Text""
                             Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Format=""N4"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? CropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options CropperOptions = new Options
    {
        SetDataOptions = new SetDataOptions
        {
            Width = 400,
            Height = 400,
        },
        ViewMode = ViewMode.Vm3
    };

    decimal _cropBoxWidth = 400;
    decimal _cropBoxHeight = 400;

    private decimal CropBoxWidth
    {
        get => _cropBoxWidth;
        set
        {
            _cropBoxWidth = value;
            CropperComponent!.SetData(new SetDataOptions
            {
                Width = _cropBoxWidth,
                Height = _cropBoxHeight
            });
            StateHasChanged();
        }
    }

    private decimal CropBoxHeight
    {
        get => _cropBoxHeight;
        set
        {
            _cropBoxHeight = value;
            CropperComponent!.SetData(new SetDataOptions
            {
                Width = _cropBoxWidth,
                Height = _cropBoxHeight
            });
            StateHasChanged();
        }
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }
</style>";

        public const string MinMaxDimensionsExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.CropEvent;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img""
                                  @ref=""cropperComponent""
                                  Src=""images/dolphin.jpg""
                                  Options=""CropperOptions""
                                  OnCropEvent=""OnCropEvent"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            @if (currentCropperData != null)
            {
                // Current crop box data
                <MudNumericField ReadOnly=""true"" Class=""mb-2"" HideSpinButtons=""true"" @bind-Value=""currentCropperData.X"" Step="".2M"" Label=""X"" Variant=""Variant.Text""
                                 Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Margin=""Margin.Dense"" Format=""N4"" />
                <MudNumericField ReadOnly=""true"" Class=""mb-2"" HideSpinButtons=""true"" @bind-Value=""currentCropperData.Y"" Label=""Y"" Step="".2M"" Variant=""Variant.Text""
                                 Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Margin=""Margin.Dense"" Format=""N4"" />
                <MudNumericField ReadOnly=""true"" Class=""mb-2"" HideSpinButtons=""true"" @bind-Value=""currentCropperData.Width"" Label=""Width"" Step="".2M"" Variant=""Variant.Text""
                                 Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Margin=""Margin.Dense"" Format=""N4"" />
                <MudNumericField ReadOnly=""true"" Class=""mb-2"" HideSpinButtons=""true"" @bind-Value=""currentCropperData.Height"" Label=""Height"" Step="".2M"" Variant=""Variant.Text""
                                 Adornment=""Adornment.End"" AdornmentText=""px"" AdornmentColor=""Color.Primary"" Margin=""Margin.Dense"" Format=""N4"" />
            }
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;
    private CropperData currentCropperData = null!;

    // Minimum and maximum cropped dimensions settings
    private static decimal minCroppedWidth = 320;
    private static decimal minCroppedHeight = 160;
    private static decimal maxCroppedWidth = 640;
    private static decimal maxCroppedHeight = 320;

    private Options CropperOptions = new Options
    {
        SetDataOptions = new SetDataOptions
        {
            Width = (minCroppedWidth + maxCroppedWidth) / 2,
            Height = (minCroppedHeight + maxCroppedHeight) / 2
        },
        ViewMode = ViewMode.Vm3
    };

    public async void OnCropEvent(JSEventData<CropEvent> cropJSEvent)
    {
        await InvokeAsync(() =>
        {
            if (cropJSEvent?.Detail is not null)
            {
                decimal width = Math.Round(cropJSEvent.Detail.Width ?? 0);
                decimal height = Math.Round(cropJSEvent.Detail.Height ?? 0);

                if (width < minCroppedWidth || height < minCroppedHeight
                    || width > maxCroppedWidth || height > maxCroppedHeight)
                {
                    decimal nWidth = Math.Max(minCroppedWidth,
                        Math.Min(maxCroppedWidth, width));
                    decimal nHeight = Math.Max(minCroppedHeight,
                        Math.Min(maxCroppedHeight, height));

                    cropperComponent!.SetData(new SetDataOptions
                    {
                        Width = nWidth,
                        Height = nHeight
                    });
                }
                else
                {
                    currentCropperData = cropJSEvent.Detail;
                    StateHasChanged();
                }
            }
        });
    }
}

<style>
    .img-container {
        max-height: 400px;
        width: 100%;
    }
</style>";

        public const string MinimumDimensionsExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.CropEvent;

<MudPaper Class=""img-container"">
    <CropperComponent Class=""big-img""
                      @ref=""cropperComponent""
                      Src=""images/Odesa.jpg""
                      Options=""cropperOptions"" />
</MudPaper>

@code {
    private CropperComponent? cropperComponent = null!;

    // Minimum relative sizes
    private static decimal minCropBoxWidth = 300;
    private static decimal minCropBoxHeight = 150;

    private Options cropperOptions = new Options
    {
        MinCropBoxWidth = minCropBoxWidth,
        MinCropBoxHeight = minCropBoxHeight,
        ViewMode = ViewMode.Vm3
    };
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }
</style>";

        public const string AbsoluteZoomExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.ZoomEvent;
@using Cropper.Blazor.Events.CropReadyEvent;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img""
                                  @ref=""cropperComponent""
                                  Src=""images/dolphin.jpg""
                                  Options=""cropperOptions""
                                  OnZoomEvent=""OnZoomEvent""
                                  OnReadyEvent=""OnCropReadyEvent"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""ZoomRatio"" Label=""Zoom Ratio""
                             Format=""N4"" Variant=""Variant.Text"" Step="".1M"" Min=""0"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""PivotX"" Label=""PivotX""
                             Format=""N4"" Variant=""Variant.Text"" Step="".1M"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""PivotY"" Label=""PivotY""
                             Format=""N4"" Variant=""Variant.Text"" Step="".1M"" />

            <MudNumericField Class=""mb-2"" @bind-Value=""OldRatio"" Label=""Old Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""CurrentRatio"" Label=""Current Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options cropperOptions = new Options
    {
        AspectRatio = 1m,
        ViewMode = ViewMode.Vm0
    };

    decimal _zoomRatio;
    decimal _pivotX;
    decimal _pivotY;

    public async void OnCropReadyEvent(JSEventData<CropReadyEvent> jSEventData)
    {
        await InvokeAsync(async () =>
        {
            ImageData imageData = await cropperComponent!.GetImageDataAsync();
            decimal initZoomRatio = imageData.Width / imageData.NaturalWidth;
            OldRatio = initZoomRatio;

            ContainerData containerData = await cropperComponent!.GetContainerDataAsync();
            // Zoom to 50% from the center of the container.
            PivotX = containerData.Width / 2;
            PivotY = containerData.Height / 2;
            ZoomRatio = 0.5m;
            StateHasChanged();
        });
    }

    private decimal ZoomRatio
    {
        get => _zoomRatio;
        set
        {
            _zoomRatio = value;
            cropperComponent?.ZoomTo(value, PivotX, PivotY);
        }
    }

    private decimal PivotX
    {
        get => _pivotX;
        set
        {
            _pivotX = value;
            cropperComponent?.ZoomTo(ZoomRatio, value, PivotY);
        }
    }


    private decimal PivotY
    {
        get => _pivotY;
        set
        {
            _pivotY = value;
            cropperComponent?.ZoomTo(ZoomRatio, PivotX, value);
        }
    }

    private decimal? OldRatio { get; set; }

    private decimal? CurrentRatio { get; set; }

    public async void OnZoomEvent(JSEventData<ZoomEvent> zoomJSEvent)
    {
        await InvokeAsync(() =>
        {
            if (zoomJSEvent.Detail is not null)
            {
                OldRatio = zoomJSEvent.Detail.OldRatio;
                CurrentRatio = zoomJSEvent.Detail.Ratio;
                StateHasChanged();
            }
        });
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string MinMaxZoomRatioExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.ZoomEvent;
@using Cropper.Blazor.Events.CropReadyEvent;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img""
                                  @ref=""cropperComponent""
                                  Src=""images/dolphin.jpg""
                                  Options=""cropperOptions""
                                  OnZoomEvent=""OnZoomEvent""
                                  OnReadyEvent=""OnCropReadyEvent"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""MinZoomRatio"" Label=""Min zoom ratio""
                             Min=""0"" Max=""MaxZoomRatio"" Variant=""Variant.Text"" Step="".1M"">
            </MudNumericField>
            <MudNumericField Class=""mb-2"" @bind-Value=""MaxZoomRatio"" Label=""Max zoom ratio""
                             Min=""MinZoomRatio ?? 0"" Variant=""Variant.Text"" Step="".1M"">
            </MudNumericField>

            <MudNumericField Class=""mb-2"" @bind-Value=""OldRatio"" Label=""Old Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""CurrentRatio"" Label=""Current Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    [Inject] private IJSRuntime? JSRuntime { get; set; }

    private CropperComponent? cropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options cropperOptions = new Options
    {
        AspectRatio = 1m,
        ViewMode = ViewMode.Vm3
    };

    private decimal? minZoomRatio = null;
    private decimal? maxZoomRatio = null;

    private decimal? MinZoomRatio
    {
        get => minZoomRatio;
        set
        {
            minZoomRatio = value;
            InvokeAsync(ApplyZoomRulesForCropperAsync);
        }
    }
    private decimal? MaxZoomRatio
    {
        get => maxZoomRatio;
        set
        {
            maxZoomRatio = value;
            InvokeAsync(ApplyZoomRulesForCropperAsync);
        }
    }

    private decimal? OldRatio { get; set; }

    private decimal? CurrentRatio { get; set; }

    public async void OnZoomEvent(JSEventData<ZoomEvent> zoomJSEvent)
    {
        await InvokeAsync(() =>
        {
            if (zoomJSEvent.Detail is not null)
            {
                OldRatio = zoomJSEvent.Detail.OldRatio;
                CurrentRatio = zoomJSEvent.Detail.Ratio;
                StateHasChanged();
            }
        });
    }

    public async void OnCropReadyEvent(JSEventData<CropReadyEvent> jSEventData)
    {
        await InvokeAsync(async () =>
        {
            ImageData imageData = await cropperComponent!.GetImageDataAsync();
            decimal initZoomRatio = imageData.Width / imageData.NaturalWidth;
            CurrentRatio = initZoomRatio;
            StateHasChanged();
        });
    }

    public async Task ApplyZoomRulesForCropperAsync()
    {
        ImageData currentImageData = await cropperComponent!.GetImageDataAsync();
        ContainerData containerData = await cropperComponent.GetContainerDataAsync();
        decimal currentZoomRatio = currentImageData.Width / currentImageData.NaturalWidth;

        if ((MinZoomRatio is not null) && (MinZoomRatio > currentZoomRatio))
        {
            cropperComponent.ZoomTo((decimal)MinZoomRatio, containerData.Width / 2, containerData.Height / 2);
        }
        else if ((MaxZoomRatio is not null) && (currentZoomRatio > MaxZoomRatio))
        {
            cropperComponent.ZoomTo((decimal)MaxZoomRatio, containerData.Width / 2, containerData.Height / 2);
        }

        await JSRuntime!.InvokeVoidAsync(""window.overrideOnZoomCropperEvent"", MinZoomRatio, MaxZoomRatio);
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string RelativeZoomExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.ZoomEvent;
@using Cropper.Blazor.Events.CropReadyEvent;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img""
                                  @ref=""cropperComponent""
                                  Src=""images/Rivne.jpg""
                                  Options=""cropperOptions""
                                  OnZoomEvent=""OnZoomEvent""
                                  OnReadyEvent=""OnCropReadyEvent"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""ZoomRatio"" Label=""Zoom Ratio""
                             Format=""N4"" Variant=""Variant.Text"" Step="".1M"" />

            <MudNumericField Class=""mb-2"" @bind-Value=""OldRatio"" Label=""Old Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""CurrentRatio"" Label=""Current Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options cropperOptions = new Options
    {
        AspectRatio = 1m,
        ViewMode = ViewMode.Vm3
    };

    decimal _zoomRatio;

    public async void OnCropReadyEvent(JSEventData<CropReadyEvent> jSEventData)
    {
        await InvokeAsync(async () =>
        {
            ImageData imageData = await cropperComponent!.GetImageDataAsync();
            decimal initZoomRatio = imageData.Width / imageData.NaturalWidth;

            _zoomRatio = initZoomRatio;
            StateHasChanged();
        });
    }

    private decimal ZoomRatio
    {
        get => _zoomRatio;
        set
        {
            _zoomRatio = value;
            cropperComponent?.Zoom(value);
        }
    }

    private decimal? OldRatio { get; set; }

    private decimal? CurrentRatio { get; set; }

    public async void OnZoomEvent(JSEventData<ZoomEvent> zoomJSEvent)
    {
        await InvokeAsync(() =>
        {
            if (zoomJSEvent.Detail is not null)
            {
                OldRatio = zoomJSEvent.Detail.OldRatio;
                CurrentRatio = zoomJSEvent.Detail.Ratio;
                StateHasChanged();
            }
        });
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string WheelZoomRatioExample = @"@using Cropper.Blazor.Models;
@using Cropper.Blazor.Events;
@using Cropper.Blazor.Events.ZoomEvent;

<MudGrid>
    <MudItem xs=""12"" sm=""8"" md=""8"" lg=""8"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img""
                                  @ref=""cropperComponent""
                                  Src=""images/Odesa.jpg""
                                  Options=""cropperOptions""
                                  OnZoomEvent=""OnZoomEvent"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""4"" md=""4"" lg=""4"">
        <MudPaper Class=""pa-2"">
            <MudNumericField Class=""mb-2"" @bind-Value=""WheelZoomRatio"" Label=""Wheel Zoom Ratio""
                             Format=""N4"" Variant=""Variant.Text"" Step="".05M"" Min=""0"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""OldRatio"" Label=""Old Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
            <MudNumericField Class=""mb-2"" @bind-Value=""CurrentRatio"" Label=""Current Ratio"" Format=""N4""
                             Variant=""Variant.Text"" HideSpinButtons=""true"" ReadOnly=""true"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options cropperOptions = new Options
    {
        AspectRatio = 1m,
        WheelZoomRatio = 0.1m,
        ViewMode = ViewMode.Vm3
    };

    private decimal? OldRatio { get; set; }

    private decimal? CurrentRatio { get; set; }

    private decimal? WheelZoomRatio
    {
        get => cropperOptions.WheelZoomRatio;
        set
        {
            cropperOptions.WheelZoomRatio = value;
            cropperComponent?.Destroy();
            cropperComponent?.InitCropper();
        }
    }

    public async void OnZoomEvent(JSEventData<ZoomEvent> zoomJSEvent)
    {
        await InvokeAsync(() =>
        {
            if (zoomJSEvent.Detail is not null)
            {
                OldRatio = zoomJSEvent.Detail.OldRatio;
                CurrentRatio = zoomJSEvent.Detail.Ratio;
                StateHasChanged();
            }
        });
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string ZoomableExample = @"@using Cropper.Blazor.Models

<MudGrid>
    <MudItem xs=""12"" sm=""9"" md=""9"" lg=""9"">
        <MudPaper Class=""pa-2"">
            <div class=""img-container"">
                <CropperComponent Class=""big-img""
                                  @ref=""cropperComponent""
                                  Src=""images/Rivne2.jpg""
                                  Options=""cropperOptions"" />
            </div>
        </MudPaper>
    </MudItem>
    <MudItem xs=""12"" sm=""3"" md=""3"" lg=""3"">
        <MudPaper Class=""pa-2"">
            <MudSwitch T=""bool?"" Class=""mb-2"" @bind-Value=""@Zoomable"" Label=""Zoomable"" Color=""Color.Primary"" />
            <MudSwitch T=""bool?"" Class=""mb-2"" @bind-Value=""@ZoomOnTouch"" Label=""Zoom On Touch"" Color=""Color.Primary"" />
            <MudSwitch T=""bool?"" Class=""mb-2"" @bind-Value=""@ZoomOnWheel"" Label=""Zoom On Wheel"" Color=""Color.Primary"" />
        </MudPaper>
    </MudItem>
</MudGrid>

@code {
    private CropperComponent? cropperComponent = null!;

    // Setting up initial dimensions of crop area
    private Options cropperOptions = new Options
    {
        AspectRatio = 1m,
        ViewMode = ViewMode.Vm3
    };

    private void ReloadCropper()
    {
        cropperComponent?.Destroy();
        cropperComponent?.InitCropper();
    }

    private bool? Zoomable
    {
        get => cropperOptions.Zoomable ?? true;
        set
        {
            cropperOptions.Zoomable = value;
            ReloadCropper();
        }
    }

    private bool? ZoomOnTouch
    {
        get => cropperOptions.ZoomOnTouch ?? true;
        set
        {
            cropperOptions.ZoomOnTouch = value;
            ReloadCropper();
        }
    }

    private bool? ZoomOnWheel
    {
        get => cropperOptions.ZoomOnWheel ?? true;
        set
        {
            cropperOptions.ZoomOnWheel = value;
            ReloadCropper();
        }
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        max-width: 100%;
    }
</style>";

        public const string DotnetWorkloadUpdateCommandExample = @"dotnet workload update";

        public const string InstallationManualComponentsExample = @"@using Cropper.Blazor.Components
@using Cropper.Blazor.Models

<CropperComponent Class=""cropper-example"" Src=""cropperblazor.png"" Options=""new Options()"" />

<style>
    .cropper-example {
        max-height: 300px;
        width: 100%;
    }
</style>";

        public const string InstallationManualCssFontsExample = @"<link href=""_content/Cropper.Blazor/cropper.min.css"" rel=""stylesheet"" />";

        public const string InstallationManualImportsExample = @"@using Cropper.Blazor.Components";

        public const string InstallationManualPackageExample = @"dotnet add package Cropper.Blazor";

        public const string VersionOverridePackageReferenceCommandExample = @"<PackageReference Include=""Package name"" VersionOverride=""New version package"" />";

        public const string UsesPreviewFromElementReferenceSelectorComponentsExample = @"@using Cropper.Blazor.Components
@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""cropper-example""
                      Src=""cropperblazor.png""
                      Options=""Options"" />
</div>
<div @ref=""ElementReference"" class=""img-example-preview"" />

<style>
    .cropper-example {
        max-height: 300px;
        width: 100%;
    }

    .img-example-preview {
        width: 100%;
        height: 300px;
        overflow: hidden;
    }

        .img-example-preview > ::deep img {
            max-width: 100%;
        }
</style>

@code {
    private Options Options = new();
    private ElementReference ElementReference;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            Options.Preview = new ElementReference[]
            {
                ElementReference
            };
        }
    }
}";

        public const string UsesPreviewFromMultipleElementReferenceSelectorComponentsExample = @"@using Cropper.Blazor.Components
@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""cropper-example""
                      Src=""cropperblazor.png""
                      Options=""Options"" />
</div>
<div @ref=""FirstElementReference"" class=""img-example-preview""></div>
<div @ref=""SecondElementReference"" class=""img-example-preview""></div>

<style>
    .cropper-example {
        max-height: 300px;
        width: 100%;
    }

    .img-example-preview {
        width: 100%;
        height: 300px;
        overflow: hidden;
    }

        .img-example-preview > ::deep img {
            max-width: 100%;
        }

</style>

@code {
    private Options Options = new();
    private ElementReference FirstElementReference;
    private ElementReference SecondElementReference;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            Options.Preview = new ElementReference[]
            {
                FirstElementReference,
                SecondElementReference
            };
        }
    }
}";

        public const string UsesPreviewFromStringSelectorComponentsExample = @"@using Cropper.Blazor.Components
@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""cropper-example""
                      Src=""cropperblazor.png""
                      Options=""Options"" />
</div>
<div class=""img-example-preview"" />

<style>
    .cropper-example {
        max-height: 300px;
        width: 100%;
    }

    .img-example-preview {
        width: 100%;
        height: 300px;
        overflow: hidden;
    }

        .img-example-preview > ::deep img {
            max-width: 100%;
        }

</style>

@code {
    private Options Options = new Options
    {
        Preview = "".img-example-preview""
    };
}";

        public const string RebuildCropperComponentExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""@src""
                      ErrorLoadImageSrc=""@_errorLoadImageSrc""
                      ErrorLoadImageClass=""cropper-error-load center""
                      IsAvailableInitCropper=""@IsAvailableInitCropper""
                      IsErrorLoadImage=""@IsErrorLoadImage""
                      OnErrorLoadImageEvent=""OnErrorLoadImageEvent""
                      @ref=""cropperComponent""
                      Options=""new Options()"" />
</div>

<InputFile id=""imageRebuildInput"" OnChange=""RebuildImageAsync"" accept=""image/*"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    #imageRebuildInput {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }

    .cropper-error-load {
        max-height: inherit;
        max-width: 100%;
    }

    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>

@code {
    private readonly string _errorLoadImageSrc = ""not-found-image.jpg"";
    private bool IsErrorLoadImage { get; set; } = false;
    private bool IsAvailableInitCropper { get; set; } = true;
    private string src = ""images/underwater-magic-world.jpeg"";
    private CropperComponent? cropperComponent = null!;

    public async Task RebuildImageAsync(InputFileChangeEventArgs inputFileChangeEventArgs)
    {
        IBrowserFile imageFile = inputFileChangeEventArgs.File;

        if (imageFile != null)
        {
            string oldSrc = src;

            src = await cropperComponent!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

            IsAvailableInitCropper = true;
            IsErrorLoadImage = false;

            cropperComponent?.Destroy();
            cropperComponent?.RevokeObjectUrlAsync(oldSrc);
        }
    }

    public void OnErrorLoadImageEvent(ErrorEventArgs errorEventArgs)
    {
        IsErrorLoadImage = true;
        Destroy();
        StateHasChanged();
    }

    private void Destroy()
    {
        cropperComponent?.Destroy();
        cropperComponent?.RevokeObjectUrlAsync(src);
    }
}";

        public const string BasicInputReplaceImageWithNewSizeExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""@Src""
                      OnLoadImageEvent=""OnLoadImageEvent""
                      ErrorLoadImageSrc=""@_errorLoadImageSrc""
                      ErrorLoadImageClass=""cropper-error-load center""
                      IsAvailableInitCropper=""@IsAvailableInitCropper""
                      IsErrorLoadImage=""@IsErrorLoadImage""
                      OnErrorLoadImageEvent=""OnErrorLoadImageEvent""
                      @ref=""CropperComponent""
                      Options=""new Options()"" />
</div>

<InputFile id=""imageReplaceInput"" OnChange=""ReplaceImageAsync"" accept=""image/*"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    #imageReplaceInput {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }

    .cropper-error-load {
        max-height: inherit;
        max-width: 100%;
    }

    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>

@code {
    private readonly string _errorLoadImageSrc = ""not-found-image.jpg"";
    private bool IsErrorLoadImage { get; set; } = false;
    private bool IsAvailableInitCropper { get; set; } = true;
    private string Src = ""images/Landscape-Color.jpg"";
    private string OldSrc = string.Empty;
    private CropperComponent? CropperComponent = null!;

    public async Task ReplaceImageAsync(InputFileChangeEventArgs inputFileChangeEventArgs)
    {
        IBrowserFile imageFile = inputFileChangeEventArgs.File;

        if (imageFile != null)
        {
            OldSrc = Src;
            string newSrc = await CropperComponent!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

            /* These conditions are required for error handling. */
            if (IsErrorLoadImage)
            {
                IsAvailableInitCropper = true;
                IsErrorLoadImage = false;
            }
            else
            {
                IsAvailableInitCropper = false;
            }

            // In the .NET 8 with new render modes, SDK parameters components are not updated timely when using 'blazor.web.js'.
            // We strongly recommend using StateHasChanged() method after changing a component's parameter,
            // but be careful with this because you're updating the entire component where there may be more than one component,
            // which can also affect performance a bit when there are too many components on the page or animations.
            // As an option, make a separate wrapper with minimal functionality in this case.
            //StateHasChanged();

            await Task.WhenAll(
                CropperComponent!.ReplaceAsync(newSrc, false).AsTask()
                // For certain platforms based on WebView in MAUI, Windows Forms and WPF Blazor Hybrids, the 'RevokeObjectUrlAsync(OldSrc)' method does not work correctly in this place.
                // We recommend clearing redundant Blob resources (old src) in the 'OnLoadImageEvent' event of cropper component or use equivalent ""Rebuild cropper"" functionality instead of replace functionality with 'hasSameSize = false' argument.
                // Note: from version 1.3.2 of the Cropper.Blazor NuGet package and 'IsAvailableInitCropper = false' triggers the 'OnLoadImageEvent' event after a successful image replacement. Previously it only worked with 'IsAvailableInitCropper = true'          
                //, CropperComponent!.RevokeObjectUrlAsync(OldSrc).AsTask()
                )
                    .ContinueWith(x =>
                    {
                        Src = newSrc;
                    });
        }
    }

    public async void OnLoadImageEvent()
    {
        if (!string.IsNullOrWhiteSpace(OldSrc))
        {
            await CropperComponent!.RevokeObjectUrlAsync(OldSrc);
        }
    }

    public void OnErrorLoadImageEvent(ErrorEventArgs errorEventArgs)
    {
        IsErrorLoadImage = true;
        Destroy();
        StateHasChanged();
    }

    private void Destroy()
    {
        CropperComponent?.Destroy();
        CropperComponent?.RevokeObjectUrlAsync(Src);
    }
}";

        public const string BasicInputReplaceImageWithSameSizeExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""@Src""
                      OnLoadImageEvent=""OnLoadImageEvent""
                      ErrorLoadImageSrc=""@_errorLoadImageSrc""
                      ErrorLoadImageClass=""cropper-error-load center""
                      IsAvailableInitCropper=""@IsAvailableInitCropper""
                      IsErrorLoadImage=""@IsErrorLoadImage""
                      OnErrorLoadImageEvent=""OnErrorLoadImageEvent""
                      @ref=""CropperComponent""
                      Options=""new Options()"" />
</div>

<InputFile id=""imageReplaceInput"" OnChange=""ReplaceImageAsync"" accept=""image/*"" />

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    #imageReplaceInput {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }

    .cropper-error-load {
        max-height: inherit;
        max-width: 100%;
    }

    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>

@code {
    private readonly string _errorLoadImageSrc = ""not-found-image.jpg"";
    private bool IsErrorLoadImage { get; set; } = false;
    private bool IsAvailableInitCropper { get; set; } = true;
    private string Src = ""images/Landscape-Color.jpg"";
    private string OldSrc = string.Empty;
    private CropperComponent? CropperComponent = null!;

    public async Task ReplaceImageAsync(InputFileChangeEventArgs inputFileChangeEventArgs)
    {
        IBrowserFile imageFile = inputFileChangeEventArgs.File;

        if (imageFile != null)
        {
            OldSrc = Src;
            string newSrc = await CropperComponent!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

            /* These conditions are required for error handling. */
            if (IsErrorLoadImage)
            {
                IsAvailableInitCropper = true;
                IsErrorLoadImage = false;
            }
            else
            {
                IsAvailableInitCropper = false;
            }

            // In the .NET 8 with new render modes, SDK parameters components are not updated timely when using 'blazor.web.js'.
            // We strongly recommend using StateHasChanged() method after changing a component's parameter,
            // but be careful with this because you're updating the entire component where there may be more than one component,
            // which can also affect performance a bit when there are too many components on the page or animations.
            // As an option, make a separate wrapper with minimal functionality in this case.
            //StateHasChanged();

            await Task.WhenAll(
                CropperComponent!.ReplaceAsync(newSrc, true).AsTask()
                // For certain platforms based on WebView in MAUI, Windows Forms and WPF Blazor Hybrids, the 'RevokeObjectUrlAsync(OldSrc)' method does not work correctly in this place.
                // We recommend clearing redundant Blob resources (old src) in the 'OnLoadImageEvent' event of cropper component or use equivalent ""Rebuild cropper"" functionality instead of replace functionality with 'hasSameSize = false' argument.
                // Note: from version 1.3.2 of the Cropper.Blazor NuGet package and 'IsAvailableInitCropper = false' triggers the 'OnLoadImageEvent' event after a successful image replacement. Previously it only worked with 'IsAvailableInitCropper = true'     
                //, cropperComponent!.RevokeObjectUrlAsync(OldSrc).AsTask()
                )
                    .ContinueWith(x =>
                    {
                        Src = newSrc;
                    });
        }
    }

    public async void OnLoadImageEvent()
    {
        if (!string.IsNullOrWhiteSpace(OldSrc))
        {
            await CropperComponent!.RevokeObjectUrlAsync(OldSrc);
        }
    }

    public void OnErrorLoadImageEvent(ErrorEventArgs errorEventArgs)
    {
        IsErrorLoadImage = true;
        Destroy();
        StateHasChanged();
    }

    private void Destroy()
    {
        CropperComponent?.Destroy();
        CropperComponent?.RevokeObjectUrlAsync(Src);
    }
}";

        public const string BasicReplaceImageWithNewSizeExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""images/Landscape-Color.jpg""
                      @ref=""CropperComponent""
                      Options=""new Options()"" />
</div>

@if (!IsReplaced)
{
    <div class=""button"" @onclick=""ReplaceImageAsync"">
        Replace image
    </div>
}

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? CropperComponent = null!;

    /* This property is only needed to display the 'Replace image' block. */
    private bool IsReplaced = false;

    public async Task ReplaceImageAsync()
    {
        IsReplaced = true;

        // In the .NET 8 with new render modes, SDK parameters components are not updated timely when using 'blazor.web.js'.
        // We strongly recommend using StateHasChanged() method after changing a component's parameter,
        // but be careful with this because you're updating the entire component where there may be more than one component,
        // which can also affect performance a bit when there are too many components on the page or animations.
        // As an option, make a separate wrapper with minimal functionality in this case.
        //StateHasChanged();

        await CropperComponent!.ReplaceAsync(""images/raspberry.jpg"", false);

        // Releases an existing object URL which was previously created by calling URL.
        // Call this method when you've finished using an object URL to let the browser know not to keep the reference to the file any longer.
        // For certain platforms based on WebView in MAUI, Windows Forms and WPF Blazor Hybrids, the 'RevokeObjectUrlAsync(OldSrc)' method does not work correctly in this place.
        // Note: from version 1.3.2 of the Cropper.Blazor NuGet package and 'IsAvailableInitCropper = false' triggers the 'OnLoadImageEvent' event after a successful image replacement. Previously it only worked with 'IsAvailableInitCropper = true'
        // We recommend clearing redundant Blob resources (old src) in the 'OnLoadImageEvent' event of cropper component or use equivalent ""Rebuild cropper"" functionality instead of replace functionality with 'hasSameSize = false' argument.
        // cropperComponent!.RevokeObjectUrlAsync(OldSrc);
    }
}";

        public const string BasicReplaceImageWithSameSizeExample = @"@using Cropper.Blazor.Models

<div class=""img-container"">
    <CropperComponent Class=""big-img""
                      Src=""images/Landscape-Color.jpg""
                      @ref=""CropperComponent""
                      Options=""new Options()"" />
</div>

@if (!IsReplaced)
{
    <div class=""button"" @onclick=""ReplaceImageAsync"">
        Replace image
    </div>
}

@* Make sure the size of the image fits perfectly into the container *@
<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }

    /* These styles are just needed for a nice button and don't related with cropper component */
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
    }
</style>

@code {
    private CropperComponent? CropperComponent = null!;

    /* This property is only needed to display the 'Replace image' block. */
    private bool IsReplaced = false;

    public async Task ReplaceImageAsync()
    {
        IsReplaced = true;

        // In the .NET 8 with new render modes, SDK parameters components are not updated timely when using 'blazor.web.js'.
        // We strongly recommend using StateHasChanged() method after changing a component's parameter,
        // but be careful with this because you're updating the entire component where there may be more than one component,
        // which can also affect performance a bit when there are too many components on the page or animations.
        // As an option, make a separate wrapper with minimal functionality in this case.
        //StateHasChanged();

        await CropperComponent!.ReplaceAsync(""images/raspberry.jpg"", true);

        // Releases an existing object URL which was previously created by calling URL.
        // Call this method when you've finished using an object URL to let the browser know not to keep the reference to the file any longer.
        // For certain platforms based on WebView in MAUI, Windows Forms and WPF Blazor Hybrids, the 'RevokeObjectUrlAsync(OldSrc)' method does not work correctly in this place.
        // Note: from version 1.3.2 of the Cropper.Blazor NuGet package and 'IsAvailableInitCropper = false' triggers the 'OnLoadImageEvent' event after a successful image replacement. Previously it only worked with 'IsAvailableInitCropper = true'
        // We recommend clearing redundant Blob resources (old src) in the 'OnLoadImageEvent' event of cropper component or use equivalent ""Rebuild cropper"" functionality instead of replace functionality with 'hasSameSize = false' argument.
        // cropperComponent!.RevokeObjectUrlAsync(OldSrc);
    }
}";

        public const string AllViewModesExample = @"@using Cropper.Blazor.Models;

<div class=""img-container"">
    <CropperComponent @ref=""cropperComponent""
                      Src=""images/Rivne.jpg""
                      Options=""cropperOptions""
                      Class=""big-img"" />
</div>

<MudButtonGroup Color=""Color.Primary"" Variant=""Variant.Filled"" OverrideStyles=""false"" Class=""mud-width-full"">
    <MudTooltip Text=""View Mode 0"" RootClass=""mud-width-full"">
        <MudButton OnClick=""@(() => SetViewMode(ViewMode.Vm0))"" Color=""Color.Primary"" Variant=""Variant.Filled"" Class=""ml-0""
                   Style=""@(cropperOptions.ViewMode == ViewMode.Vm0 ? ""background-color: var(--mud-palette-primary-darken)"" : """")"" FullWidth=""true"">
            VM0
        </MudButton>
    </MudTooltip>
    <MudTooltip Text=""View Mode 1"" RootClass=""mud-width-full"">
        <MudButton OnClick=""@(() => SetViewMode(ViewMode.Vm1))"" Color=""Color.Primary"" Variant=""Variant.Filled"" Class=""ml-0""
                   Style=""@(cropperOptions.ViewMode == ViewMode.Vm1 ? ""background-color: var(--mud-palette-primary-darken)"" : """")"" FullWidth=""true"">
            VM1
        </MudButton>
    </MudTooltip>
    <MudTooltip Text=""View Mode 2"" RootClass=""mud-width-full"">
        <MudButton OnClick=""@(() => SetViewMode(ViewMode.Vm2))"" Color=""Color.Primary"" Variant=""Variant.Filled"" Class=""ml-0""
                   Style=""@(cropperOptions.ViewMode == ViewMode.Vm2 ? ""background-color: var(--mud-palette-primary-darken)"" : """")"" FullWidth=""true"">
            VM2
        </MudButton>
    </MudTooltip>
    <MudTooltip Text=""View Mode 3"" RootClass=""mud-width-full"">
        <MudButton OnClick=""@(() => SetViewMode(ViewMode.Vm3))"" Color=""Color.Primary"" Variant=""Variant.Filled"" Class=""ml-0""
                   Style=""@(cropperOptions.ViewMode == ViewMode.Vm3 ? ""background-color: var(--mud-palette-primary-darken)"" : """")"" FullWidth=""true"">
            VM3
        </MudButton>
    </MudTooltip>
</MudButtonGroup>

@code {
    private CropperComponent? cropperComponent = null!;

    private Options cropperOptions = new Options
    {
        ViewMode = ViewMode.Vm3
    };

    public void SetViewMode(ViewMode viewMode)
    {
        cropperOptions.ViewMode = viewMode;
        cropperComponent?.Destroy();
        cropperComponent?.InitCropper();
    }
}

<style>
    .big-img {
        max-height: 400px;
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }

    .img-container {
        max-height: 400px;
        width: 100%;
    }
</style>";

    }
}
