---
name: Build, run tests, code linting

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches-ignore:
    - master

jobs:
  code-quality-check:
    name: Check code quality
    uses: CropperBlazor/Cropper.Blazor/.github/workflows/build-test-template.yml@dev
    secrets: inherit

  code-linting:
    permissions:
      # To write linting fixes
      contents: write
      # To write Super-linter status checks
      statuses: write
    name: Code linting
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false
          
      - name: Super-Linter
        uses: super-linter/super-linter@v8.2.1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

           OUTPUT_FOLDER: Reports
           OUTPUT_DETAILS: detailed
           LOG_LEVEL: WARN

           VALIDATE_ALL_CODEBASE: true
           VALIDATE_MARKDOWN: false
           VALIDATE_JAVASCRIPT_PRETTIER: false
           VALIDATE_BIOME_FORMAT: false
           VALIDATE_BIOME_LINT: false
           VALIDATE_DOTNET_SLN_FORMAT_STYLE: false
           VALIDATE_DOTNET_SLN_FORMAT_ANALYZERS: false

           FIX_CSS_PRETTIER: true
           FIX_JSON_PRETTIER: true
           FIX_HTML_PRETTIER: true
           FIX_MARKDOWN_PRETTIER: true
           FIX_YAML_PRETTIER: true
           FIX_NATURAL_LANGUAGE: true
           FIX_GITHUB_ACTIONS_ZIZMOR: true

           FILTER_REGEX_EXCLUDE: '(\W|^)(obj/|bin/)|(\W|^)(.*([.]min[.]css))($)|(\W|^)(.*([.]min[.]js))($)'
           FILTER_REGEX_INCLUDE: '/github/workspace/src/Cropper.Blazor/.*|/github/workspace/.github/.*'

           JSCPD_CONFIG_FILE: '.jscpd.json'
           HTML_FILE_NAME: '.htmlhintrc'
           CSS_FILE_NAME: '.stylelintrc.json'
           GITHUB_ACTIONS_ZIZMOR_CONFIG_FILE: 'zizmor.yaml'

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: ${{secrets.COMMIT_USER_NAME}}
          commit_user_email: ${{secrets.COMMIT_USER_EMAIL}}
