name: Build & Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - dependabot/**
  pull_request:
    branches:
    - dependabot/**

jobs:
  build-and-test:
    name: Build & Test
    uses: CropperBlazor/Cropper.Blazor/.github/workflows/build-test-template.yml@dev
    with:
      publish-coverage: false
