name: Build & Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - dependabot/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Build & Test
        uses: .github/workflows/build-test-template.yml@develop

